s1 = input("Pleas, input  you string?:")
s1 = s1.lower()
s2 = s1.replace(".", "").replace(",", "").replace("!", "").replace("?", "").replace(":", "").replace(";", "")
s2 = s2.rstrip()
print(s1)
print(s2.rstrip())

s3 = input("With what do you want to replace?""\n")
s3 = s3.lower()
s3 = s3.rstrip()
print(f"Was found at position: {s1.find(s3)}")

s4 = input("With what do you want to replace? \n")
s4 = s4.rstrip()
print("Here is your result :""\n " + s2.replace(s3, s4))
